// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9EMTCJ_GBV7QXJbqv3XMa0HBXkBoDO1Y',
    appId: '1:61300629629:web:6749524efaa1e337aa1114',
    messagingSenderId: '61300629629',
    projectId: 'nssapp-c5d8f',
    authDomain: 'nssapp-c5d8f.firebaseapp.com',
    storageBucket: 'nssapp-c5d8f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUMglOp-a2A72q8_6FW8QNUv_0H0aTl1c',
    appId: '1:61300629629:android:13e7fa332173a09aaa1114',
    messagingSenderId: '61300629629',
    projectId: 'nssapp-c5d8f',
    storageBucket: 'nssapp-c5d8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPeeZRh44XkBpBU78YVRuwGMw252oYFLI',
    appId: '1:61300629629:ios:5e6f05c0f39bebbbaa1114',
    messagingSenderId: '61300629629',
    projectId: 'nssapp-c5d8f',
    storageBucket: 'nssapp-c5d8f.appspot.com',
    iosClientId: '61300629629-nj0bniagsli8uceggpt45qb32fhbrst7.apps.googleusercontent.com',
    iosBundleId: 'com.nssapp.nss',
  );
}
